name: Export Reflex Project
description: Export a Reflex project with a cache
inputs:
  args:
    description: Arguments to `reflex export`.
    required: false
  project-root:
    description: The path to the root of your Reflex project. May be absolute or relative to the current working directory. Defaults to the current working directory.
    required: false
    default: .
  interpreter:
    description: The path to the Python interpreter the action should use. May be absolute or relative to `project-root`.

runs:
  using: composite
  steps:
    - name: Fail on Windows
      if: ${{ runner.os == 'Windows' }}
      shell: bash
      run: |
        echo "::error::This action does not currently support Windows runners."
        exit 1

    - name: Save Environment
      shell: bash
      run: cat ${GITHUB_ENV} > ${{ runner.temp }}/.reflex-export-original-env

    - name: Set Working Directory
      shell: bash
      run: echo REFLEX_EXPORT_CWD=$(realpath ${{ inputs.project-root }}) >> ${GITHUB_ENV}

    - name: Check Project Root
      shell: bash
      run: |
        if [ ! -f rxconfig.py ]; then
          echo "::error::It doesn't look like this directory is the root of a Reflex project. Maybe you should've passed project-root?"
          exit 1
        fi
      working-directory: ${{ env.REFLEX_EXPORT_CWD }}

    - name: Set Python Interpreter
      if: ${{ inputs.interpreter }}
      shell: bash
      run: echo "UV_PYTHON=${{ inputs.interpreter }}" >> ${GITHUB_ENV}

    - name: Set Up uv
      uses: astral-sh/setup-uv@v4

    - name: Get Web Directory
      id: web
      shell: uv run --no-project python {0}
      run: |
        import os
        from reflex.utils.prerequisites import get_web_dir
        
        print(f"web={get_web_dir().absolute()}", file=open(os.getenv("GITHUB_OUTPUT"), "a"))
      working-directory: ${{ env.REFLEX_EXPORT_CWD }}

    - name: Compute Cache Key
      id: compute-key
      shell: bash
      run: uv run --no-project ${{ github.action_path }}/key.py
      working-directory: ${{ env.REFLEX_EXPORT_CWD }}

    - name: Restore Cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ steps.web.outputs.web }}
        key: ${{ steps.compute-key.outputs.key }}

    - name: Export Project
      shell: bash
      run: uv run --no-project reflex export ${{ inputs.args }}
      working-directory: ${{ env.REFLEX_EXPORT_CWD }}
      env:
        LOGLEVEL: ${{ env.LOGLEVEL || runner.debug && 'debug' || 'default' }}

    - name: Recompute Cache Key
      id: recompute-key
      shell: bash
      run: uv run --no-project ${{ github.action_path }}/key.py
      working-directory: ${{ env.REFLEX_EXPORT_CWD }}

    - name: Save Cache
      uses: actions/cache/save@v4
      with:
        path: ${{ steps.web.outputs.web }}
        key: ${{ steps.recompute-key.outputs.key }}

    - name: Restore Environment
      shell: bash
      run: cat ${{ runner.temp }}/.reflex-export-original-env > ${GITHUB_ENV}