name: Export Reflex Project
inputs:
  args:
    description: Arguments to `reflex export`.
    required: false


runs:
  using: composite
  steps:
    - name: Exit on Windows
      if: ${{ runner.os == "Windows" }}
      shell: bash
      run: |
        echo "::error::This action does not currently support Windows runners."
        exit 1

    - name: Set Up uv
      uses: astral-sh/setup-uv@v3

    - name: Initialize Reflex
      shell: bash
      run: uv run reflex init

    - name: Get Paths
      id: paths
      shell: uv run --with github-action-utils python {0}
      run: |
        import github_action_utils as gha
        from reflex.config import get_config
        from reflex.utils.prerequisites import get_web_dir
        
        gha.set_output("web", get_web_dir().absolute())
        gha.set_output("bun", get_config().bun_path.absolute())

    - name: Restore Reflex Cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ steps.paths.outputs.web }}
        key: ${{ runner.os }}-reflex-

    - name: Export Project
      shell: bash
      run: ${{ steps.paths.outputs.bun }} install --cwd ${{ steps.paths.outputs.web }} --frozen-lockfile; uv run reflex export ${{ inputs.args }}

    - name: Get Cache Key Hash
      id: hash
      shell: uv run --with github-action-utils python {0}
      run: |
        import hashlib
        
        import github_action_utils as gha
        from reflex.utils.prerequisites import get_web_dir
        
        key_hash = ""
        web = get_web_dir().absolute()
        
        for lockfile in ["bun.lockb", "package-lock.json"]:
            fp = web / lockfile
            
            if fp.exists():
                key_hash += hashlib.sha256(fp.read_bytes())
        
        gha.set_output("hash", key_hash)

    - name: Save Reflex Cache
      uses: actions/cache/save@v4
      with:
        path: ${{ steps.paths.outputs.web }}
        key: ${{ runner.os }}-reflex-${{ steps.hash.outputs.hash }}
