name: Export Reflex Project
description: Export a Reflex project with a cache
inputs:
  args:
    description: Arguments to `reflex export`.
    required: false
  project-root:
    description: The root of your Reflex project, if not the current working directory.
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: Set Up uv
      uses: astral-sh/setup-uv@v3

    - name: Install rxahelper
      shell: uv run bash {0}
      run: uv tool install '${{ github.action_path }}/rxahelper' --with reflex==$(pip show reflex | grep 'Version' | cut -d ' ' -f 2)

    - name: Set Working Directory
      shell: bash
      run: echo REFLEX_EXPORT_CWD=$(realpath ${{ inputs.project-root }}) >> ${GITHUB_ENV}

    - name: Check Project Root
      shell: bash
      run: |
        if [ ! -f rxconfig.py ]; then
          echo "::error::It doesn't look like this directory is the root of a Reflex project. Maybe you should've passed project-root?"
          exit 1
        fi
      working-directory: ${{ env.REFLEX_EXPORT_CWD }}

    - name: Get Web Directory
      id: web
      shell: bash
      run: rxahelper get-web
      working-directory: ${{ env.REFLEX_EXPORT_CWD }}

    - name: Get Cache Key I
      id: key-1
      shell: bash
      run: rxahelper get-key
      working-directory: ${{ env.REFLEX_EXPORT_CWD }}

    - name: Restore Cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ steps.web.outputs.get_web }}
        key: ${{ steps.key-1.outputs.key }}

    - name: Export Project
      shell: bash
      run: uv run reflex export ${{ inputs.args }}
      working-directory: ${{ env.REFLEX_EXPORT_CWD }}
      env:
        LOGLEVEL: ${{ env.LOGLEVEL || runner.debug && 'debug' || 'default' }}

    - name: Get Cache Key II
      id: key-2
      shell: bash
      run: rxahelper get-key
      working-directory: ${{ env.REFLEX_EXPORT_CWD }}

    - name: Save Cache
      uses: actions/cache/save@v4
      with:
        path: ${{ steps.web.outputs.web }}
        key: ${{ steps.key-2.outputs.key }}
