name: Export Reflex Project
inputs:
  args:
    description: Arguments to `reflex export`.
    required: false
  project-root:
    description: The root of your Reflex project, if not the current working directory.
    default: .

runs:
  using: composite
  steps:
    - name: Get Working Directory
      shell: bash
      run: echo REFLEX_EXPORT_CWD=$(realpath ${{ inputs.project-root }}) >> ${GITHUB_ENV}

    - name: Enable Debug Logging
      if: ${{ runner.debug }}
      shell: bash
      run: echo REFLEX_EXPORT_LOG_LEVEL=debug >> ${GITHUB_ENV}
        

    - name: Check for rxconfig.py
      shell: bash
      run: | 
        if [ ! -f rxconfig.py ]; then
          echo "::error::It doesn't look like the current directory is the root of a Reflex project. Maybe you should've passed project-root?"
          exit 1
        fi
      working-directory: ${{ env.REFLEX_EXPORT_CWD }}

    - name: Set Up uv
      uses: astral-sh/setup-uv@v3

    - name: Initialize Reflex
      shell: bash
      run: uv run reflex init
      working-directory: ${{ env.REFLEX_EXPORT_CWD }}
      env:
        LOG_LEVEL: ${{ env.REFLEX_EXPORT_LOG_LEVEL }}

    - name: Get Web Directory
      id: web
      shell: uv run --with hachitool python {0}
      run: |
        import hachitool
        from reflex.config import get_config
        from reflex.utils.prerequisites import get_web_dir
        
        hachitool.set_output(web=get_web_dir().absolute())
      working-directory: ${{ env.REFLEX_EXPORT_CWD }}

    - name: Get Cache Key I
      id: key-1
      shell: bash
      run: uv run --with hachitool ${{ github.action_path }}/key.py
      working-directory: ${{ env.REFLEX_EXPORT_CWD }}

    - name: Restore Reflex Cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ steps.web.outputs.web }}
        key: ${{ steps.key-1.outputs.key }}

    - name: Export Project
      shell: bash
      run: uv run reflex export ${{ runner.debug && '--loglevel debug' || '' }} ${{ inputs.args }}
      working-directory: ${{ env.REFLEX_EXPORT_CWD }}
      env:
        LOG_LEVEL: ${{ env.REFLEX_EXPORT_LOG_LEVEL }}

    - name: Get Cache Key II
      id: key-2
      shell: bash
      run: uv run --with hachitool ${{ github.action_path }}/key.py
      working-directory: ${{ env.REFLEX_EXPORT_CWD }}

    - name: Save Reflex Cache
      uses: actions/cache/save@v4
      with:
        path: ${{ steps.web.outputs.web }}
        key: ${{ steps.key-2.outputs.key }}
