on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Tag Release
        uses: celsiusnarhwal/tag-action-release@v1
