name: Tests

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos"]
        python: ["3.10", "3.11", "3.12", "3.13"]
        pm: ["pip", "uv", "poetry", "pdm", "pipenv"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Set Up uv
        uses: astral-sh/setup-uv@v4

      - name: Install Package Manager
        if: ${{ matrix.pm != 'pip' && matrix.pm != 'uv' }}
        run: uv tool install ${{ matrix.pm }}

      - name: Install Reflex (pip)
        if: ${{ matrix.pm == 'pip' }}
        run: pip install reflex

      - name: Install Reflex (uv)
        if: ${{ matrix.pm == 'uv' }}
        run: uv init && uv add reflex

      - name: Install Reflex (pipenv)
        if: ${{ matrix.pm == 'pipenv' }}
        run: pipenv install reflex
        env:
          PIPENV_VENV_IN_PROJECT: true

      - name: Install Reflex (PDM/Poetry)
        if: ${{ matrix.pm == 'poetry' || matrix.pm == 'pdm' }}
        shell: bash
        run: ${{ matrix.pm }} init -n && ${{ matrix.pm }} add reflex

      - if: ${{ matrix.pm == 'poetry' }}
        shell: bash
        id: interpreter
        run: echo "interpreter=$(poetry env info --executable)" >> ${GITHUB_OUTPUT}

      - name: Initialize Reflex Project
        run: uv run --no-project reflex init --template blank
        env:
          UV_PYTHON: ${{ steps.interpreter.outputs.interpreter }}

      - name: Export Reflex Project
        uses: celsiusnarhwal/reflex-export@main
        with:
          args: --loglevel debug
          interpreter: ${{ steps.interpreter.outputs.interpreter }}
