name: Test Action

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos"]
        python: ["3.10", "3.11", "3.12", "3.13"]
        pm: ["pip", "uv", "poetry", "pdm"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Set Up uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install Package Manager
        if: ${{ matrix.pm != 'pip' && matrix.pm != 'uv' }}
        run: uv tool install ${{ matrix.pm }}

      - name: Install Reflex (pip)
        if: ${{ matrix.pm == 'pip' }}
        run: pip install reflex

      - name: Install Reflex (uv/PDM)
        if: ${{ matrix.pm == 'uv' || matrix.pm == 'pdm' }}
        run: uv init && ${{ matrix.pm }} add reflex

      - name: Install Reflex (Poetry)
        if: ${{ matrix.pm == 'poetry' }}
        run: ${{ matrix.pm }} init -n && poetry add reflex

      - name: Initialize Reflex Project
        run: uv run reflex init --template blank || poetry run reflex init --template blank

      - name: Export Reflex Project
        uses: celsiusnarhwal/reflex-export@main
        with:
          args: --loglevel debug
