name: Test Action

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos", "windows"]
        pm: ["pip", "uv", "poetry", "pdm"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Set Up uv
        uses: astral-sh/setup-uv@v3

      - name: Install Package Manager
        if: ${{ matrix.pm != 'pip' && matrix.pm != 'uv' }}
        run: uv tool install ${{ matrix.pm }}

      - name: Install Reflex (pip)
        if: ${{ matrix.pm == 'pip' }}
        run: pip install reflex

      - name: Install Reflex (uv)
        if: ${{ matrix.pm == 'uv' }}
        run: uv init && uv add reflex

      - name: Install Reflex (Poetry/PDM)
        if: ${{ matrix.pm == 'poetry' || matrix.pm == 'pdm' }}
        run: ${{ matrix.pm }} init -n && ${{ matrix.pm }} add reflex

      - name: Initialize Reflex Project
        run: uv run reflex init --template blank || poetry run reflex init --template blank

      - name: Export Reflex Project
        uses: celsiusnarhwal/reflex-export@main
        with:
          args: --loglevel debug
