name: Test Action

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pm: ["pip", "uv", "poetry", "pdm"]
    env:
      UV_NO_CONFIG: true
    steps:
      - name: Set Up uv
        uses: astral-sh/setup-uv@v3

      - name: Install Reflex (pip)
        if: ${{ matrix.pm == 'pip' }}
        run: pip install reflex

      - name: Install Reflex (uv)
        if: ${{ matrix.pm == 'uv' }}
        run: uv init && uv add reflex

      - name: Install Reflex (Poetry/PDM)
        if: ${{ matrix.pm == 'poetry' || matrix.pm == 'pdm' }}
        run: uvx ${{ matrix.pm }} init -n && uvx ${{ matrix.pm }} add reflex
        env:
          POETRY_VIRTUALENVS_IN_PROJECT: true

      - name: Initialize Reflex Project
        run: uv run reflex init --template blank

      - name: Export Reflex Project
        uses: celsiusnarhwal/reflex-export@main
        with:
          args: --loglevel debug
